Tests for data sets
lisds/project-daylight-robbery pull request #19
Opened 2023-12-13 20:42 UTC by palpatel0

Co-authored by: Tom Fox tom.fox@lis.ac.uk

2023-12-13 22:03 UTC, TomWFox commented on projtools/tests/test_data.py
> +    #assert list(np.sort(data.lsoa.index.get_level_values(4).unique())) == list(np.sort(data.ward.index.get_level_values(3).unique())) #LSOA is missing Rape, Other Sexual Offences and Historical Frau
```suggestion
def test_data_consistency():
    """Tests that the data is the same between the different data sets"""
    assert list(np.sort(data.borough.index.get_level_values(0).unique())) == list(np.sort(data.ward.index.get_level_values(2).unique()))
    # LSOA is missing Historical Fraud and Forgery and Sexual Offences
    assert list(np.sort(np.append(data.lsoa.index.get_level_values(3).unique().to_numpy(), ['Sexual Offences', 'Historical Fraud and Forgery']))) == list(np.sort(data.ward.index.get_level_values(2).unique()))
    assert list(np.sort(data.borough.index.get_level_values(1).unique())) == list(np.sort(data.ward.index.get_level_values(3).unique()))
    # LSOA is missing Rape, Other Sexual Offences and Historical Fraud and Forgery
    assert list(np.sort(np.append(data.lsoa.index.get_level_values(4).unique().to_numpy(), ['Rape', 'Other Sexual Offences', 'Historical Fraud and Forgery']))) == list(np.sort(data.ward.index.get_level_values(3).unique()))
```

2023-12-17 15:37 UTC, palpatel0 commented on projtools/tests/test_data.py
> +    #assert list(np.sort(data.lsoa.index.get_level_values(4).unique())) == list(np.sort(data.ward.index.get_level_values(3).unique())) #LSOA is missing Rape, Other Sexual Offences and Historical Frau
how do i edit this code?
I think it would be worth adding comments on what exactly the tests are comparing

2023-12-17 16:00 UTC, TomWFox commented on projtools/tests/test_data.py
> +    #assert list(np.sort(data.lsoa.index.get_level_values(4).unique())) == list(np.sort(data.ward.index.get_level_values(3).unique())) #LSOA is missing Rape, Other Sexual Offences and Historical Frau
You can edit in the browser by going to "files changed" and clicking edit

or you can `git switch` your branch to palpatel0:tests and make the change locally, then push

2023-12-17 16:01 UTC, TomWFox commented on projtools/tests/test_data.py
> +    #assert list(np.sort(data.lsoa.index.get_level_values(4).unique())) == list(np.sort(data.ward.index.get_level_values(3).unique())) #LSOA is missing Rape, Other Sexual Offences and Historical Frau
but if you mean you want to edit my changes you could first commit, then change whatever you want, or just copy and paste my changes into you local copy, make your changes, and mark this convo as resolved

2023-12-17 17:18 UTC, palpatel0 commented on projtools/tests/test_data.py
> +    assert list(np.sort(np.append(data.lsoa.index.get_level_values(4).unique().to_numpy(), ['Rape', 'Other Sexual Offences', 'Historical Fraud and Forgery']))) == list(np.sort(data.ward.index.get_lev
```suggestion
    """Tests that the data is the same between the different data sets"""
    assert list(np.sort(data.borough.index.get_level_values(0).unique())) == list(np.sort(data.ward.index.get_level_values(2).unique())) #This test checks that the borough and ward data sets have the same categories for offences
    # LSOA is missing Historical Fraud and Forgery and Sexual Offences
    assert list(np.sort(np.append(data.lsoa.index.get_level_values(3).unique().to_numpy(), ['Sexual Offences', 'Historical Fraud and Forgery']))) == list(np.sort(data.ward.index.get_level_values(2).unique())) #This test checks that the LSOA and ward datasets have the same categories for offences. Two of the missing categories are added to the LSOA list
    assert list(np.sort(data.borough.index.get_level_values(1).unique())) == list(np.sort(data.ward.index.get_level_values(3).unique())) #This test checks that the borough and ward data sets have the same list of offences
    # LSOA is missing Rape, Other Sexual Offences and Historical Fraud and Forgery
    assert list(np.sort(np.append(data.lsoa.index.get_level_values(4).unique().to_numpy(), ['Rape', 'Other Sexual Offences', 'Historical Fraud and Forgery']))) == list(np.sort(data.ward.index.get_level_values(3).unique())) #This test checks that the LSOA and ward datasets have the same list of offences. Three of the missing offences are added to the LSOA list.
```

2023-12-17 17:24 UTC, TomWFox commented
ready for review?

2023-12-17 18:17 UTC, palpatel0 commented
> ready for review?

yes, please :)

2023-12-17 18:35 UTC, TomWFox requested changes
Thanks for adding those comments, I think it's better for readability to have them above, rather than at the end of the lines

2023-12-17 18:35 UTC, TomWFox commented on projtools/tests/test_data.py
> +    assert list(np.sort(np.append(data.lsoa.index.get_level_values(4).unique().to_numpy(), ['Rape', 'Other Sexual Offences', 'Historical Fraud and Forgery']))) == list(np.sort(data.ward.index.get_lev
```suggestion
def test_data_consistency():
    """Tests that the data is the same between the different data sets"""
    # This test checks that the borough and ward data sets have the same categories for offences
    assert list(np.sort(data.borough.index.get_level_values(0).unique())) == list(np.sort(data.ward.index.get_level_values(2).unique()))
    # This test checks that the LSOA and ward datasets have the same categories for offences. Two of the missing categories (Historical Fraud and Forgery and Sexual Offences) are added to the LSOA list
    assert list(np.sort(np.append(data.lsoa.index.get_level_values(3).unique().to_numpy(), ['Sexual Offences', 'Historical Fraud and Forgery']))) == list(np.sort(data.ward.index.get_level_values(2).unique()))
    #This test checks that the borough and ward data sets have the same list of offences
    assert list(np.sort(data.borough.index.get_level_values(1).unique())) == list(np.sort(data.ward.index.get_level_values(3).unique()))
    #This test checks that the LSOA and ward datasets have the same list of offences. Three of the missing offences (Rape, Other Sexual Offences and Historical Fraud and Forgery) are added to the LSOA list.
    assert list(np.sort(np.append(data.lsoa.index.get_level_values(4).unique().to_numpy(), ['Rape', 'Other Sexual Offences', 'Historical Fraud and Forgery']))) == list(np.sort(data.ward.index.get_level_values(3).unique()))
```

2023-12-17 19:44 UTC, TomWFox approved these changes

2023-12-17 19:44 UTC, merged